apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: crypto-pet
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: crypto-pet
        visualize: "true"
    spec:
      containers:
        - name: crypto-pet-pod
          image: test/crypto-pet
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  labels:
    visualize: "true"
  name: crypto-pet-service
spec:
  selector:
    app: crypto-pet
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP
---
  apiVersion: traefik.containo.us/v1alpha1
  kind: Middleware
  metadata:
    name: prod-rate-limit
  spec:
    rateLimit:
      average: 30
      burst: 50